=== Merry2706/Klausurvorbereitung2017/Vorlesung.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Veranstaltungsliste (Veranstaltung)+>
<!ELEMENT Veranstaltung (Name,Studienjahr,SWS,ECTS,Pruefungsleistung,Dozent,Veranstaltungsart)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Studienjahr (#PCDATA)>
<!ELEMENT SWS (#PCDATA)>
<!ELEMENT ECTS (#PCDATA)>
<!ELEMENT Pruefungsleistung (#PCDATA)>
<!ELEMENT Dozent (#PCDATA)>
<!ELEMENT Veranstaltungsart (#PCDATA)>
<!ATTLIST Veranstaltungsart kuerzel CDATA #REQUIRED>

=== Merry2706/Klausurvorbereitung2017/Vorlesung.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Veranstaltungsliste SYSTEM "Vorlesung.dtd" >
<Veranstaltungsliste>
  <Veranstaltung>
    <Name>Name</Name>
    <Studienjahr>Studienjahr</Studienjahr>
    <SWS>SWS</SWS>
    <ECTS>ECTS</ECTS>
    <Pruefungsleistung>Pruefungsleistung</Pruefungsleistung>
    <Dozent>Dozent</Dozent>
    <Veranstaltungsart kuerzel="">Veranstaltungsart</Veranstaltungsart>
  </Veranstaltung>
</Veranstaltungsliste>
